# Generated by Django 3.1.7 on 2021-03-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('contributors', models.CharField(max_length=350)),
                ('iswc', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
