# Generated by Django 3.1.7 on 2021-03-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singleview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='MusicalWorks',
        ),
    ]
